/*
 * File: app/view/Customer1.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Vidly.view.Customer1', {
    extend: 'Ext.window.Window',
    alias: 'widget.vmcustomer1',

    requires: [
        'Ext.form.Panel',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.form.field.Checkbox',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Date',
        'Ext.toolbar.Paging'
    ],

    height: 273,
    width: 440,
    layout: 'fit',
    title: 'Cusotmers',

    items: [
        {
            xtype: 'form',
            bodyPadding: 10,
            layout: {
                type: 'vbox',
                align: 'stretch'
            },
            dockedItems: [
                {
                    xtype: 'toolbar',
                    flex: 1,
                    dock: 'top',
                    ui: 'i21-toolbar',
                    items: [
                        {
                            xtype: 'button',
                            itemId: 'btnNew',
                            ui: 'i21-button-toolbar-small',
                            text: 'New'
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnSave',
                            ui: 'i21-button-toolbar-small',
                            text: 'Save'
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnSearch',
                            ui: 'i21-button-toolbar-small',
                            text: 'Search'
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnDelete',
                            ui: 'i21-button-toolbar-small',
                            text: 'Delete'
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnUndo',
                            ui: 'i21-button-toolbar-small',
                            text: 'Undo'
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnClose',
                            ui: 'i21-button-toolbar-small',
                            text: 'Close'
                        }
                    ]
                },
                {
                    xtype: 'ipagingstatusbar',
                    flex: 1,
                    dock: 'bottom'
                }
            ],
            items: [
                {
                    xtype: 'tabpanel',
                    flex: 1,
                    bodyCls: 'i21-tab',
                    activeTab: 0,
                    items: [
                        {
                            xtype: 'panel',
                            title: 'Details',
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'container',
                                    margins: '',
                                    margin: '0 5 5 0',
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            itemId: 'txtCusotmerName',
                                            margin: '0 5 5 0',
                                            fieldLabel: 'Customer Name: ',
                                            labelWidth: 130
                                        },
                                        {
                                            xtype: 'checkboxfield',
                                            flex: 1,
                                            itemId: 'chkIsSubscribedToNewsletter',
                                            fieldLabel: 'Is Subscribed To Newsletter: ',
                                            labelWidth: 130
                                        },
                                        {
                                            xtype: 'gridcombobox',
                                            columns: [
                                                {
                                                    dataIndex: 'intMembershipTypeId',
                                                    dataType: 'numeric',
                                                    text: 'Membership Type Id',
                                                    hidden: true
                                                },
                                                {
                                                    dataIndex: 'strMembershipTypeName',
                                                    dataType: 'string',
                                                    text: 'Membership Type',
                                                    flex: 1
                                                },
                                                {
                                                    dataIndex: 'intSignUpFee',
                                                    dataType: 'numeric',
                                                    text: 'Sign Up Fee',
                                                    flex: 1
                                                }
                                            ],
                                            itemId: 'cboMembershipType',
                                            fieldLabel: 'Membership Type: ',
                                            labelWidth: 130,
                                            displayField: 'strMembershipTypeName',
                                            valueField: 'strMembershipTypeName'
                                        },
                                        {
                                            xtype: 'textfield',
                                            flex: 1,
                                            itemId: 'txtMembershipTypeId',
                                            fieldLabel: 'Membership Type Id',
                                            labelWidth: 130
                                        },
                                        {
                                            xtype: 'datefield',
                                            flex: 1,
                                            itemId: 'dtmBirthdate',
                                            fieldLabel: 'Birthdate: ',
                                            labelWidth: 130
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            itemId: 'pnlAuditLog',
                            layout: 'fit',
                            title: 'Audit Log',
                            items: [
                                {
                                    xtype: 'auditlogtree'
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]

});