/*
 * File: app/view/MembershipTypeViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Vidly.view.MembershipTypeViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.vmmembershiptype',

    show : function() {
        "use strict";
 
        var me = this,
        win = me.getView();
        win.show();
 
        var context = win.context ? win.context.initialize() : me.setupContext();
        context.data.load();
    },

    setupContext: function() {
        var me = this,
            win = me.getView();
 
        win.context = Ext.create('iRely.Engine', {
            window : win,
            store  : Ext.create('Vidly.store.MembershipType'),
            singleGridMgr: Ext.create('iRely.grid.Manager', {
                grid:  win.down('grid'),
                title: 'Membership Type Grid',
                columns: [
                    {
                        xtype: 'gridcolumn',
                        itemId: 'colName',
                        dataType: 'string',
                        dataIndex: 'strMembershipTypeName',
                        text: 'Membership Type Name',
                        flex: 1,
                        required: true,
                        editor: {
                            xtype: 'textfield',
                            itemId: 'txtName',
                            required: true,
                        }
                    },
                    {
                        xtype: 'gridcolumn',
                        itemId: 'colSignUpFee',
                        dataType: 'numeric',
                        dataIndex: 'intSignUpFee',
                        text: 'SignUp Fee',
                        flex: 1,
                        editor: {
                            xtype: 'textfield',
                            itemId: 'txtSignUpFee'
                        }
                    },
                    {
                        xtype: 'gridcolumn',
                        itemId: 'colintDurationInMonths',
                        dataType: 'numeric',
                        dataIndex: 'intDurationInMonths',
                        text: 'Duration In Months',
                        flex: 1,
                        editor: {
                            xtype: 'textfield',
                            itemId: 'txtintDurationInMonths'
                        }
                    },
                    {
                        xtype: 'gridcolumn',
                        itemId: 'colintDiscountRate',
                        dataType: 'numeric',
                        dataIndex: 'intDiscountRate',
                        text: 'Discount Rate',
                        flex: 1,
                        editor: {
                            xtype: 'textfield',
                            itemId: 'txtintDiscountRate'
                        }
                    }
                ]
            })
        });
 
        return win.context;
    }
});
