/*
 * File: app/view/Movie1ViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Vidly.view.Movie1ViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.vmmovie1',

    requires: [
        'GlobalComponentEngine.view.AuditLogTree'
    ],

    config: {
        binding: {
            txtMovieName: '{current.strMovieName}',
            txtGenreId: '{current.intGenreId}',
            dtmReleaseDate: '{current.dtmReleaseDate}',
            dtmDateAdded: '{current.dtmDateAdded}',
            txtNumberInStock: '{current.intNumberInStock}',
            txtNumberAvailable: '{current.intNumberAvailable}',
            cboGenre: {
                value: '{current.strGenreName}',
                origValueField: 'intGenreId',
                store: '{genre}'
            },
        },
    },

    show: function(config){
        "use strict";

        var me = this,
        win = me.getView(),
        action = config && config.action;

        if (config) {

            win.show();
            var context = win.context ? win.context.initialize() : me.setupContext({ window: win });
            //var context = win.context ? win.context.initialize() : me.setupContext();

            if (config.action === 'new') {
                context.data.addRecord();
            } else {
                if (config.id) {
                    config.filters = [{
                        column: 'intMovieId',
                        value: config.id
                    }];
                }
                context.data.load({
                    filters: config.filters
                });
            }
        }
    },

    setupContext : function(options){
        "use strict";
        var me = this,
            win = this.getView(),
            store = Ext.create('Vidly.store.Movie', { pageSize: 1 });

        win.context = Ext.create('iRely.Engine', {
            window : win,
            store  : store,
            enableAudit: true,
            binding: me.config.binding
        });

        return win.context;
    }
});
