/*
 * File: app/view/PagingStatusbar.js
 *
 * This file was generated by Sencha Architect version 4.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Vidly.view.PagingStatusbar', {
    extend: 'Ext.toolbar.Paging',
    alias: 'widget.pagingstatusbar',

    requires: [
        'Ext.button.Button',
        'Ext.form.Label',
        'Ext.toolbar.Fill'
    ],

    itemId: 'tlbPaging',
    width: 1264,
    inputItemWidth: 35,
    prependButtons: true,

    items: [
        {
            xtype: 'button',
            tabIndex: -1,
            itemId: 'btnHelpDummy',
            iconCls: 'small-help',
            tooltip: 'Click to get help on this form'
        },
        {
            xtype: 'button',
            tabIndex: -1,
            itemId: 'btnHelpDummy1',
            iconCls: 'small-support',
            tooltip: 'Click to get help on this form'
        },
        {
            xtype: 'button',
            tabIndex: -1,
            itemId: 'btnHelpDummy2',
            iconCls: 'small-light-bulb-off',
            tooltip: 'Click to get help on this form'
        },
        {
            xtype: 'label',
            itemId: 'lblStatusDummy',
            margin: '0 5',
            text: 'Ready'
        },
        {
            xtype: 'tbfill'
        }
    ]

});