/*
 * File: app/view/RentalViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Vidly.view.RentalViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.vmrental',

    config: {
        binding: {
            cboCustomer: {
                value: '{current.strCustomerName}',
                origValueField: 'intCustomerId',
                store: '{customer}'
            },
            dtmDateRented: {
                value: '{current.dtmDateRented}'
            },
            gridRentalDetail: {
                colMovieId: {
                    dataIndex: 'intMovieId'
                },
                colDateReturned: {
                    dataIndex: 'dtmDateReturned'
                },
                colMovieName: {
                    dataIndex : 'strMovieName',
                    editor: {
                        origValueField:'intMovieId',
                        store: '{movie}'
                    }
                }
            }
        }
    },

    show: function(config){
        "use strict";

        var me = this,
        win = me.getView(),
        action = config && config.action;

        if (config) {

            win.show();

            var context = win.context ? win.context.initialize() : me.setupContext();
            
            if (config.action === 'new') {
                context.data.addRecord();
            } else {
                if (config.id) {
                    config.filters = [{
                        column: 'intRentalHeaderId',
                        value: config.id
                    }];
                }
                context.data.load({
                    filters: config.filters
                });
            }
        }
    },

    setupContext: function(){
        "use strict";

        var me = this,
        win = me.getView();

        win.context = Ext.create('iRely.Engine', {
            window: win,
            store: Ext.create('Vidly.store.Rental', {pageSize: 1}),
            enableAudit: true,
            binding: me.config.binding,
            details: [{
                key: 'tblVMRentalDetail',
                lazy: true,
                component: Ext.create('iRely.grid.Manager', {
                    grid: win.down('#gridRentalDetail')
                })
            }]
        });

        return win.context;
    }
});
