/*
 * File: app/view/Rental.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Vidly.view.Rental', {
    extend: 'Ext.window.Window',
    alias: 'widget.vmrental',

    requires: [
        'Ext.form.Panel',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Date',
        'Ext.grid.Panel',
        'Ext.grid.column.Date',
        'Ext.view.Table',
        'Ext.grid.plugin.CellEditing',
        'Ext.toolbar.Paging',
        'GlobalComponentEngine.view.AdvanceSearchGrid'
    ],

    height: 455,
    width: 876,
    layout: 'fit',
    title: 'Rental',

    items: [
        {
            xtype: 'form',
            bodyPadding: 10,
            layout: {
                type: 'vbox',
                align: 'stretch'
            },
            dockedItems: [
                {
                    xtype: 'toolbar',
                    flex: 1,
                    dock: 'top',
                    ui: 'i21-toolbar',
                    items: [
                        {
                            xtype: 'button',
                            itemId: 'btnNew',
                            ui: 'i21-button-toolbar-small',
                            text: 'New'
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnSave',
                            ui: 'i21-button-toolbar-small',
                            text: 'Save'
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnFind',
                            ui: 'i21-button-toolbar-small',
                            text: 'Search'
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnDelete',
                            ui: 'i21-button-toolbar-small',
                            text: 'Delete'
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnClose',
                            ui: 'i21-button-toolbar-small',
                            text: 'Close'
                        }
                    ]
                },
                // {
                //     xtype: 'ipagingstatusbar',
                //     flex: 1,
                //     dock: 'bottom'
                // }
            ],
            items: [
                {
                    xtype: 'tabpanel',
                    flex: 1,
                    bodyCls: 'i21-tab',
                    activeTab: 0,
                    items: [
                        {
                            xtype: 'panel',
                            title: 'Details',
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    itemId: 'ctnHeader',
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'gridcombobox',
                                            columns: [
                                                {
                                                    dataIndex: 'intCustomerId',
                                                    dataType: 'numeric',
                                                    text: 'Cusotmer Id',
                                                    flex: 1,
                                                    hidden: true
                                                },
                                                {
                                                    dataIndex: 'strCustomerName',
                                                    dataType: 'string',
                                                    text: 'Customer Name',
                                                    flex: 1
                                                }
                                            ],
                                            flex: 1,
                                            itemId: 'cboCustomer',
                                            fieldLabel: 'Customer Name: ',
                                            labelWidth: 130,
                                            displayField: 'strCustomerName',
                                            valueField: 'strCustomerName'
                                        },
                                        {
                                            xtype: 'datefield',
                                            flex: 1,
                                            itemId: 'dtmDateRented',
                                            fieldLabel: 'Date Rented: ',
                                            labelWidth: 130
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    flex: 2,
                                    itemId: 'ctnDetails',
                                    layout: 'fit',
                                    items: [
                                        {
                                            xtype: 'frmadvancesearchgrid',
                                            itemId: 'gridRentalDetail',
                                            title: 'Rental Detail',
                                            columns: [
                                                {
                                                    xtype: 'gridcolumn',
                                                    flex: 1,
                                                    hidden: true,
                                                    itemId: 'colMovieId',
                                                    dataIndex: 'string',
                                                    text: 'Movie Id',
                                                    editor: {
                                                        xtype: 'textfield'
                                                    }
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    flex: 1,
                                                    itemId: 'colMovieName',
                                                    dataIndex: 'strMovieName',
                                                    text: 'Movie Name',
                                                    editor: {
                                                        xtype: 'gridcombobox',
                                                        columns: [
                                                            {
                                                                dataIndex: 'intMovieId',
                                                                dataType: 'numeric',
                                                                text: 'Movie Id',
                                                                flex: 1,
                                                                hidden: true
                                                            },
                                                            {
                                                                dataIndex: 'strMovieName',
                                                                dataType: 'string',
                                                                text: 'Movie Name'
                                                            }
                                                        ],
                                                        itemId: 'cboMovieName',
                                                        displayField: 'strMovieName',
                                                        valueField: 'strMovieName'
                                                    }
                                                },
                                                {
                                                    xtype: 'datecolumn',
                                                    flex: 1,
                                                    itemId: 'colDateReturned',
                                                    dataIndex: 'date',
                                                    text: 'Date Returned',
                                                    editor: {
                                                        xtype: 'datefield'
                                                    }
                                                }
                                            ],
                                            plugins: [
                                                {
                                                    ptype: 'cellediting',
                                                    clicksToEdit: 1
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            itemId: 'pnlAuditLog',
                            layout: 'fit',
                            title: 'Audit Log',
                            items: [
                                {
                                    xtype: 'auditlogtree'
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]

});